# Generated by Django 5.2.1 on 2025-10-27 22:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('employment_status', models.CharField(choices=[('tetap', 'Tetap'), ('probation', 'Probation')], max_length=10)),
                ('permanent_date', models.DateField()),
                ('place_of_birth', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(choices=[('islam', 'Islam'), ('kristen', 'Kristen'), ('katolik', 'Katolik'), ('protestan', 'Protestan'), ('hindu', 'Hindu'), ('budha', 'Budha')], max_length=10)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('devorced', 'Devorced'), ('widowed', 'Widowed')], max_length=10)),
                ('national_id_number', models.CharField(max_length=16)),
                ('family_card_number', models.CharField(max_length=16)),
                ('bpjs_employment', models.CharField(max_length=16)),
                ('bpjs_healt', models.CharField(max_length=16)),
                ('tax_id', models.CharField(blank=True, max_length=16, null=True)),
                ('blood_type', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=3)),
                ('phone', models.CharField(max_length=16)),
                ('private_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(blank=True, max_length=6, null=True)),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('office', 'Office'), ('production', 'Production')], max_length=20)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Employee_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('registered_address', 'Registered_address'), ('current_address', 'Current_address')], max_length=20)),
                ('address', models.CharField(max_length=120)),
                ('village', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('province', models.CharField(max_length=32)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee_address',
                'verbose_name_plural': 'Employee_addresss',
            },
        ),
        migrations.CreateModel(
            name='Employee_family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('relationship', models.CharField(choices=[('child', 'Child'), ('father_in_law', 'Father_in_law'), ('mother', 'Wife'), ('mother_in_law', 'Mother_in_law'), ('spouse', 'Spouse')], max_length=15)),
                ('date_of_birth', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee_family',
                'verbose_name_plural': 'Employee_familys',
            },
        ),
        migrations.CreateModel(
            name='Employee_studied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=8, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee_studied',
                'verbose_name_plural': 'Employee_studieds',
            },
        ),
        migrations.CreateModel(
            name='Subdepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.departement')),
            ],
            options={
                'verbose_name': 'Subdepartement',
                'verbose_name_plural': 'Subdepartements',
            },
        ),
        migrations.CreateModel(
            name='Employee_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position')),
                ('subdepartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.subdepartement')),
            ],
            options={
                'verbose_name': 'Employee_history',
                'verbose_name_plural': 'Employee_historys',
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.unit'),
        ),
    ]
