# Generated by Django 5.2.1 on 2025-12-14 03:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_family',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee_history',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee_history',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee_history',
            name='subdepartement',
        ),
        migrations.RemoveField(
            model_name='employee_studied',
            name='employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='bpjs_healt',
            new_name='bpjs_health',
        ),
        migrations.AlterField(
            model_name='departement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='employee.unit'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='family_card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permanent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdepartement',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepartements', to='employee.departement'),
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('registered', 'Registered Address'), ('current', 'Current Address')], max_length=20)),
                ('address', models.CharField(max_length=120)),
                ('village', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('province', models.CharField(max_length=32)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Address',
                'verbose_name_plural': 'Employee Addresses',
            },
        ),
        migrations.CreateModel(
            name='EmployeeFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('relationship', models.CharField(choices=[('child', 'Child'), ('father_in_law', 'Father-in-law'), ('mother', 'Wife'), ('mother_in_law', 'Mother-in-law'), ('spouse', 'Spouse')], max_length=15)),
                ('date_of_birth', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee_family',
                'verbose_name_plural': 'Employee_familys',
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employee.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position')),
                ('subdepartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_histories', to='employee.subdepartement')),
            ],
            options={
                'verbose_name': 'Employee History',
                'verbose_name_plural': 'Employee Histories',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStudied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=8, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee  Studied',
                'verbose_name_plural': 'Employee Studied Record',
            },
        ),
        migrations.DeleteModel(
            name='Employee_address',
        ),
        migrations.DeleteModel(
            name='Employee_family',
        ),
        migrations.DeleteModel(
            name='Employee_history',
        ),
        migrations.DeleteModel(
            name='Employee_studied',
        ),
    ]
