# Generated by Django 5.2.1 on 2025-12-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_family_employee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departement',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Subdepartement',
            new_name='Subdepartment',
        ),
        migrations.AlterModelOptions(
            name='employeefamily',
            options={'verbose_name': 'Employee Family', 'verbose_name_plural': 'Employee Families'},
        ),
        migrations.AlterModelOptions(
            name='employeestudied',
            options={'verbose_name': 'Employee Education', 'verbose_name_plural': 'Employee Education Record'},
        ),
        migrations.RenameField(
            model_name='employeehistory',
            old_name='subdepartement',
            new_name='subdepartment',
        ),
        migrations.RenameField(
            model_name='subdepartment',
            old_name='departement',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='employeefamily',
            name='relationship',
            field=models.CharField(choices=[('child', 'Child'), ('father', 'Father'), ('mother', 'Mother'), ('father_in_law', 'Father-in-law'), ('mother_in_law', 'Mother-in-law'), ('spouse', 'Spouse')], max_length=15),
        ),
    ]
