# Generated by Django 5.2.1 on 2025-12-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_departement_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, help_text='Tanggal resmi keluar', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_type',
            field=models.CharField(blank=True, choices=[('resign', 'Resign'), ('terminated', 'Terminated'), ('retired', 'Retired')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
