# Generated by Django 5.2.1 on 2025-12-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_exit_date_employee_exit_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_working_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], help_text='Keep empty if unknown', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, help_text='The date employee truely exit', null=True),
        ),
        migrations.AddConstraint(
            model_name='employeehistory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee',), name='unique_active_history_per_employee'),
        ),
    ]
