# Generated by Django 5.2.1 on 2025-12-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_bpjs_employment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('destination', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_succces', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='employee.employeeonboarding')),
            ],
        ),
    ]
