# Generated by Django 5.2.1 on 2026-01-02 01:03

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_add_emergency_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload employee photo (JPG, PNG, max 5MB)', null=True, upload_to='employee_photos/', validators=[employee.models.validate_image_size]),
        ),
    ]
