# Generated by Django 5.2.1 on 2026-01-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Nama perusahaan tempat bekerja sebelumnya', max_length=100)),
                ('position', models.CharField(help_text='Posisi/jabatan di perusahaan tersebut', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Departemen/divisi tempat bekerja', max_length=100, null=True)),
                ('start_date', models.DateField(help_text='Tanggal mulai bekerja')),
                ('end_date', models.DateField(help_text='Tanggal selesai bekerja')),
                ('job_description', models.TextField(blank=True, help_text='Deskripsi pekerjaan dan tanggung jawab', null=True)),
                ('reason_for_leaving', models.CharField(blank=True, help_text='Alasan meninggalkan pekerjaan', max_length=200, null=True)),
                ('salary_range', models.CharField(blank=True, help_text='Range gaji (opsional)', max_length=50, null=True)),
                ('supervisor_name', models.CharField(blank=True, help_text='Nama atasan langsung', max_length=100, null=True)),
                ('supervisor_contact', models.CharField(blank=True, help_text='Kontak atasan (email/telepon)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Work Experience',
                'verbose_name_plural': 'Employee Work Experiences',
                'ordering': ['-end_date', '-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='work_experience_start_before_end')],
            },
        ),
    ]
