# Generated by Django 5.2.1 on 2025-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_departement_alter_item_options_item_cpu_item_display_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='itemunit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemunit',
            name='serial_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
