# Generated by Django 5.2.1 on 2025-07-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_options_itemunit_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemunit',
            options={'verbose_name': 'ItemUnit', 'verbose_name_plural': 'ItemUnits'},
        ),
        migrations.AddField(
            model_name='itemunit',
            name='asset_number',
            field=models.CharField(default='GTI-PC-0076', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemunit',
            name='status',
            field=models.CharField(choices=[('in_warehouse', 'In Warehouse'), ('in_use', 'In Use'), ('borrowed', 'Borrowed'), ('damaged', 'Damaged')], max_length=20),
        ),
    ]
