# Generated by Django 5.2.1 on 2025-08-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemunit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
    ]
