# Generated by Django 5.2.1 on 2025-08-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_area_remove_location_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.area'),
        ),
    ]
