# Generated by Django 5.2.1 on 2025-10-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='auto_generate_next',
            field=models.BooleanField(default=True),
        ),
    ]
